services:
  db:
    image: postgres:16
    container_name: openbucket-db
    environment:
      POSTGRES_USER: openbucket
      POSTGRES_PASSWORD: openbucket
      POSTGRES_DB: openbucket
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - openbucket_data:/var/lib/postgresql/data
    restart: unless-stopped

  openbucket:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: openbucket
    depends_on:
      - db
    environment:
      PORT: 8080
      DATABASE: postgres://openbucket:openbucket@db:5432/openbucket?sslmode=disable&search_path=core
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  openbucket_data:
